version: "3.4"
services:
  iec-api:
    tty: true
    image: "iec-api"
    stdin_open: true
    build:
      context: .
      target: "development"
    volumes:
      - ".:/iec_api"
#    env_file: .env